name: .NET

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Bison.CLI
        run: dotnet restore ./src/Bison.CLI/Bison.CLI.csproj

      - name: Restore SimpleDB
        run: dotnet restore ./src/SimpleDB/SimpleDB.csproj

      - name: Restore Bison.CSVDBService
        run: dotnet restore ./src/Bison.CSVDBService/Bison.CSVDBService.csproj

      - name: Build Bison.CLI
        run: dotnet build ./src/Bison.CLI/Bison.CLI.csproj --no-restore

      - name: Build SimpleDB
        run: dotnet build ./src/SimpleDB/SimpleDB.csproj --no-restore

      - name: Build Bison.CSVDBService
        run: dotnet build ./src/Bison.CSVDBService/Bison.CSVDBService.csproj --no-restore

      - name: Run server for tests
        run: dotnet run --project ./src/Bison.CSVDBService/Bison.CSVDBService.csproj

      - name: Test
        run: dotnet test
