name: .NET

on:
  push:
    branches: [ "main", "P2-2.b" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Bison.CLI
      run: dotnet restore Bison.CLI

    - name: Restore SimpleDB
      run: dotnet restore SimpleDB

    - name: Build Bison.CLI
      run: dotnet build Bison.CLI --no-restore

    - name: Build SimpleDB
      run: dotnet build SimpleDB --no-restore